In [1]:
# importing libray
import pandas as pd
import pickle
import numpy as np
import matplotlib.pyplot as plt
import time

In [2]:
# creating a func for select k best
def selectKbest(indep_X, dep_Y,n):
    # Refer - https://scikit-learn.org/stable/modules/feature_selection.htmlhttps://scikit-learn.org/stable/modules/feature_selection.html
    from sklearn.feature_selection import SelectKBest,chi2
    test = SelectKBest(score_func = chi2, k=n) # parameters are chi2 and k value
    fit1=test.fit(indep_X,dep_Y)# fitting input and output to the model
    selectkbest= fit1.transform(indep_X)  # # Transform indep_X to select only for k value features
    return selectkbest

In [3]:
# creating the function for std scalar and input output split
def split_scalar(indep_X,dep_Y):
    from sklearn.preprocessing import StandardScaler
    from sklearn.model_selection import train_test_split
    X_train,X_test,Y_train,Y_test = train_test_split(indep_X,dep_Y,test_size = 0.25, random_state = 0)
    sc = StandardScaler()
    X_train=sc.fit_transform(X_train)
    X_test=sc.transform(X_test)
    return X_train,X_test,Y_train,Y_test

In [4]:
# creating a function for r2 and testing
def r2_prediction(regressor, X_test, Y_test):
    test_pred = regressor.predict(X_test)
    from sklearn.metrics import r2_score
    r2 = r2_score(Y_test, test_pred)
    return r2

In [5]:
# function for linear reg
def linear_reg(X_train,Y_train,X_test):
    from sklearn.linear_model import LinearRegression
    regressor = LinearRegression()
    regressor.fit(X_train,Y_train)
    r2 = r2_prediction(regressor,X_test,Y_test)
    return r2
# func for svm
def svm_reg(X_train,Y_train,X_test):
    from sklearn.svm import SVR
    regressor = SVR(kernel ='linear')
    regressor.fit(X_train,Y_train)
    r2 = r2_prediction(regressor,X_test,Y_test)
    return r2
# func for decision tree
def decisiontree_reg(X_train,Y_train,X_test):
    from sklearn.tree import DecisionTreeRegressor
    regressor = DecisionTreeRegressor(random_state= 0)
    regressor.fit(X_train,Y_train)
    r2 =r2_prediction(regressor,X_test,Y_test)
    return r2
# func for randomforest
def randomforest_reg(X_train,Y_train,X_test):
    from sklearn.ensemble import RandomForestRegressor
    regressor = RandomForestRegressor(n_estimators = 10, random_state = 0)
    regressor.fit(X_train,Y_train)
    r2 = r2_prediction(regressor, X_test,Y_test)
    return r2

In [6]:
# creating func fot df to store the value
def selectK_reg(r2score_lin,r2score_svm,r2score_dt,r2score_rf):
    df = pd.DataFrame(index =['ChiSquare'],columns=['Linear','SVM','DecisionTree','RandomForest'])
    df
    for number,idex in enumerate(df.index):
        df['Linear'][idex] = r2score_lin[number]
        df['SVM'][idex] = r2score_svm[number]
        df['DecisionTree'][idex]= r2score_dt[number]
        df['RandomForest'][idex]= r2score_rf[number]
    return df

In [7]:
dataset = pd.read_csv("Pre_loan_data.csv",index_col=None)
dataframe = dataset
dataframe

,Age,Experience,Income,Family,CCAvg,Education,Mortgage,Personal Loan,Securities Account,CD Account,Online,CreditCard
0,25,1,4.083,4,1.6,1,0,0,1,0,0,0
1,45,19,2.833,3,1.5,1,0,0,1,0,0,0
2,39,15,0.917,1,1.0,1,0,0,0,0,0,0
3,35,9,8.333,1,2.7,2,0,0,0,0,0,0
4,35,8,3.750,4,1.0,2,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...
4995,29,3,3.333,1,1.9,3,0,0,0,0,1,0
4996,30,4,1.250,4,0.4,1,85,0,0,0,1,0
4997,63,39,2.000,2,0.3,3,0,0,0,0,0,0
4998,65,40,4.083,3,0.5,2,0,0,0,0,1,0
4999,28,4,6.917,3,0.8,1,0,0,0,0,1,1

In [8]:
indep_X=dataframe.drop('Personal Loan', axis =1)
dep_Y =dataframe['Personal Loan']

In [9]:
kbest=selectKbest(indep_X,dep_Y,6)
r2score_lin=[]
r2score_svm=[]
r2score_dt=[]
r2score_rf=[]

In [ ]:
X_train,X_test,Y_train,Y_test=split_scalar(kbest,dep_Y)
for i in kbest:
    r2_lin=linear_reg(X_train,Y_train,X_test)
    r2score_lin.append(r2_lin)
    
    r2_svm=svm_reg(X_train,Y_train,X_test)
    r2score_svm.append(r2_svm)
    
    r2_dT=decisiontree_reg(X_train,Y_train,X_test)
    r2score_dt.append(r2_dT)
    
    r2_rf=randomforest_reg(X_train,Y_train,X_test)
    r2score_rf.append(r2_rf)

In [ ]:
result = selectK_reg(r2score_lin,r2score_svm,r2score_dt,r2score_rf)

In [ ]:
# result #9

In [ ]:
result #6